[build]
  command = "cd frontend && npm run build"
  publish = "frontend/dist"

[functions]
  # This is the directory that contains the serverless functions.
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200