[build]
  command = "npm run build"
  publish = "frontend/dist"

[functions]
  # This is the directory that contains the serverless functions.
  directory = "functions"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200